version: '3.8'

services:
  vezlo-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: vezlo-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    env_file:
      - ./server/.env
    volumes:
      - ./server/logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vezlo-network

networks:
  vezlo-network:
    driver: bridge
